import { Router } from 'express';
import { RoadmapController } from '../controllers/RoadmapController';
import { authMiddleware } from '../middleware/auth';

const router = Router();

/**
 * @openapi
 * /api/roadmap/generate:
 *   post:
 *     tags:
 *       - Roadmap
 *     summary: Generate a personalized learning roadmap
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - goal
 *             properties:
 *               goal:
 *                 type: string
 *               experienceLevel:
 *                 type: string
 *     responses:
 *       200:
 *         description: Roadmap generated successfully
 */
router.post('/generate', RoadmapController.generateRoadmap as any);

/**
 * @openapi
 * /api/roadmap/my-paths:
 *   get:
 *     tags:
 *       - Roadmap
 *     summary: List all roadmaps generated by the current user
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: List of user roadmaps retrieved
 */
router.get('/my-paths', RoadmapController.listUserRoadmaps as any);

export default router;
